export const data = [
  {
    id: 0,
    code: "CBA.AX",
    company: "COMMONEALTH BANK",
    price: 45.54,
    value: 87556,
    Change: 0,
    percentChange: 0,
  },
  {
    id: 1,
    code: "GPT.AP",
    company: "TECHCOM BANK",
    price: 22.54,
    value: 77777,
    Change: 0,
    percentChange: 0,
  },
  {
    id: 2,
    code: "GTA.AT",
    company: "AGRIBANK BANK",
    price: 41.55,
    value: 15550,
    Change: 0,
    percentChange: 0,
  },
  {
    id: 3,
    code: "GPA.AT",
    company: "VIETTIN BANK",
    price: 74.25,
    value: 34631,
    Change: 0,
    percentChange: 0,
  },
  {
    id: 4,
    code: "MGR.AT",
    company: "MB BANK",
    price: 54.25,
    value: 74631,
    Change: 0,
    percentChange: 0,
  },
  {
    id: 5,
    code: "PDT.AT",
    company: "SAKO BANK",
    price: 54.25,
    value: 74631,
    Change: 0,
    percentChange: 0,
  },
  {
    id: 6,
    code: "GTA.AT",
    company: "MONO BANK",
    price: 54.25,
    value: 74631,
    Change: 0,
    percentChange: 0,
  },
];
